import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import getLayout from '../components/getLayoutFun'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons8-news.svg" />
      </Head>
              <h1 className={styles.welcome}>Welcome to Our news website !</h1>

    </div>
  )
}

Home.getLayout = getLayout
